adam_betas:
- 0.9
- 0.98
adaptive_cutoff_sigma: -3.5
batch_size: 256
clip_grad: 0.0
clip_norm: 1.0
cos_abs: 0
domain: real
dropout: 0.0
embedding_dim:
- 128
encoder_name: latticeformer
experiment_name: max/opt_bandgap
ff_dim: 512
frame_method: max
freeze_bn_epochs: 0
gauss_lb_real: 0.5
gauss_lb_reci: 0.5
gauss_state: q
head_num: 8
k_dim: 0
lattice_range: 2
loss_func: L1
lr: 0.0005
lr_sch: inverse_sqrt_nowarmup
minimum_range: true
model_checkpoint_save_top_k: 1
model_dim: 128
n_epochs: 2000
norm_type: 'no'
normalize_gauss: true
normalize_targets: scale_bias
num_layers: 4
num_workers: 0
optimizer: adamw
param_file: crystalframer/default_jarvis.json
pooling: avr
positive_func_beta: 0.1
pre_pooling_op: 'no'
pretrained_model: null
reproduciblity_state: 2
save_path: result/crystalframer/JARVIS
scale_grad: 0.0
scale_real:
- 1.4
scale_reci:
- 2.2
sch_params:
- 4000.0
seed: 123
swa_epochs: 50
symm_break_noise: 1.0e-05
t_activation: relu
t_fixup_init: true
target_set: jarvis__dft_3d_2021
targets: opt_bandgap
train_filter_max: 0
train_filter_min: 0
train_percent_check: 1.0
use_cgcnn_feat: false
use_cuda_code: true
v_dim: 0
val_percent_check: 1.0
value_pe_angle_coef: 1.0
value_pe_angle_real: 64
value_pe_angle_wscale: 4.0
value_pe_dist_coef: 1.0
value_pe_dist_max: -10.0
value_pe_dist_real: 64
value_pe_dist_reci: 0
value_pe_dist_wscale: 1.0
value_pe_wave_real: 0
value_pe_wave_reci: 0
weight_decay: 1.0e-05
